### PR TITLE
Update heimdall backend url

### PR DESCRIPTION
**Pull request by portdeveloper**
## Description

Uses the new url structure and can use https://heimdall-api-v2.fly.dev/ as an env var.

The new url is already added as an env var to the project at vercel.
It is live at: https://abi-ninja-v2-ewpdbpx46-buidlguidldao.vercel.app/

## Additional Information

- [ ] I have read the [contributing docs](https://github.com/BuidlGuidl/abi.ninja/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/BuidlGuidl/abi.ninja/pulls)

## Related Issues

_Closes #133 

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Review by Pabl0cks — APPROVED** [review]
GJ @portdeveloper!! Looking good to me, just a couple of points to check:

- `https://heimdall-api-v2.fly.dev/` was not working for me, had to delete last '/' character to leave it like: `https://heimdall-api-v2.fly.dev`
- When we merge, we'll need to update `NEXT_PUBLIC_HEIMDALL_URL` value in Vercel, right? Or how does the update workflow look for this PR to be seamless to the user?

**Comment by portdeveloper** [comment]
> GJ @portdeveloper!! Looking good to me, just a couple of points to check:
> 
> * `https://heimdall-api-v2.fly.dev/` was not working for me, had to delete last '/' character to leave it like: `https://heimdall-api-v2.fly.dev`
> * When we merge, we'll need to update `NEXT_PUBLIC_HEIMDALL_URL` value in Vercel, right? Or how does the update workflow look for this PR to be seamless to the user?

Ah sorry I forgot to mention it! We already have the env var ready at vercel but it only affects this branch
image

So before we merge, we can just delete the old one and make this new env var available on all deployments.

I think this is the best way to handle this but I am open to ideas!

**Comment by technophile-04** [comment]
Tested it out nicely and works great!! Thanks @portdeveloper! I think @carletex can update the env + merge this PR 

So the steps could be: 

1. Update the `NEXT_PUBLIC_HEIMDALL_URL`  env for abi.ninja on vercel with : 

    ```bash
    https://heimdall-api-v2.fly.dev
    ```

2. Merge this branch, and it should trigger autodeploy on vercel along with this changes + the env set in vercel.

**Review by technophile-04 — APPROVED** [review]

**Comment by carletex** [comment]
Done!

**Pull request merged**
