### PR TITLE
wagmi v2 migration

### PR DESCRIPTION
**Pull request by technophile-04**
### Description: 

Migrate to wagmi V2

Here is the deployed address contract address on sepolia to test : 

```shell
0xE009aea21af005e6B531B5f4a8f909C64A0c596d
```

Other chains also works, to test you can add Celo 

Then past this address: 

```shell
0xcebA9300f2b948710d2653dD7B07f33A8B32118C
```

https://celoscan.io/token/0xceba9300f2b948710d2653dd7b07f33a8b32118c#code

And abi manually : 

<details>

<summary>
USDC ABI : 
</summary>

```shell
[{"inputs":[{"internalType":"address","name":"implementationContract","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"previousAdmin","type":"address"},{"indexed":false,"internalType":"address","name":"newAdmin","type":"address"}],"name":"AdminChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"implementation","type":"address"}],"name":"Upgraded","type":"event"},{"stateMutability":"payable","type":"fallback"},{"inputs":[],"name":"admin","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newAdmin","type":"address"}],"name":"changeAdmin","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"implementation","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"}],"name":"upgradeTo","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"upgradeToAndCall","outputs":[],"stateMutability":"payable","type":"function"}]
```

</details>

### CODE REVIEW

**Review by portdeveloper — APPROVED** [review]
LGTM!!! Thanks @technophile-04 that was really quick!

There is one problem though, which does not stem from the code changed.

The chains returned from viem have duplicates. That is why we are getting the duplicate keys error in the deployment. I will open an issue on their repo.

On a second note, they are well aware of the duplication, maybe we should be adding logic that filters Linea Goerli Testnet and X1 Testnet-195


As always, amazing work Shiv 🫡

**Review by Pabl0cks — COMMENTED** [review]
Just documenting in case it happens to others in the future, when doing `yarn install` on my laptop (Windows 11) I was facing an error. 

I tried with a fresh repo just in case, and it was installing OK on `main` but with error on this branch. This was the error:

```
➤ YN0007: │ utf-8-validate@npm:6.0.4 must be built because it never has been bef
ore or the last one failed
➤ YN0009: │ utf-8-validate@npm:6.0.4 couldn't be built successfully (exit code 1
, logs can be found here: C:\Users\Pablo\AppData\Local\Temp\xfs-4ce6ad89\build.l
og)
➤ YN0000: └ Completed in 2s 425ms
➤ YN0000: Failed with errors in 3s 656ms
```
This was the log: [build.log](https://github.com/user-attachments/files/15980220/build.log)

Got fixed installing Visual Studio Build Tools 2022 with "Desktop development with C++".

**Review by Pabl0cks — APPROVED** [review]
Awesome job @technophile-04 !! And nice catch @portdeveloper 🙌🙌

Looks good to me!

**Comment by technophile-04** [comment]
Fixed https://github.com/BuidlGuidl/abi.ninja/issues/124, seems like button was nested in button `MethodSelector` component  which is discouraged in html semantic checkout https://stackoverflow.com/a/39386695 

Solved it and also made sure everything accessible: 


Uploading Screen Recording 2024-06-27 at 9.11.32 PM.mov…

**Comment by Pabl0cks** [comment]
> Fixed https://github.com/BuidlGuidl/abi.ninja/issues/124, seems like button was nested in button MethodSelector component which is discouraged in html semantic checkout https://stackoverflow.com/a/39386695

Now is working great with no console error 🙌

I've just realized of a strange bug with the balance and explorer link for chains not included in Popular networks (maybe is something wrong with my cache). 

It's showing the last popular network balance and explorer instead of refreshing with the actual network you selected (Celo in this case).

Steps to reproduce:
- Load a sepolia contract => `0xfDc1306fEC0C26Ed7012F863983cC138b1Ccb528`
- Go back to home and load a Celo contract => `0xF25fA0D4896271228193E782831F6f3CFCcF169C`
- Balance loaded is my balance from Sepolia for that address. If I click in RainbowKit dropdown and "View on Block Explorer" it opens Sepolia block explorer

Video:

https://www.loom.com/share/888a1cd8e140490199b278afb40d8c5e?sid=af7a20e6-92af-41dc-bba4-a633cd330647

**Comment by technophile-04** [comment]
Ohh thanks Pablo!! nice catch! fixed at https://github.com/BuidlGuidl/abi.ninja/pull/121/commits/1ddd9a0f101e22274e15972ae041fb7bfaefd575

**Comment by Pabl0cks** [comment]
> Ohh thanks Pablo!! nice catch! fixed at https://github.com/BuidlGuidl/abi.ninja/commit/1ddd9a0f101e22274e15972ae041fb7bfaefd575

Thank you for the fast fix! Looking great now 🙌

**Comment by technophile-04** [comment]
Merging this thanks all!!

**Pull request merged**
