### PR TITLE
Improve structs UI 

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

Demo : 

https://github.com/BuidlGuidl/abi.ninja/assets/80153681/3500a484-225b-43f3-8d7b-345ff84f8c66

Here is example [opensea contract](https://etherscan.io/address/0x00000000006c3852cbEf3e08E8dF289169EdE581#code) address on mainnet : 0x00000000006c3852cbEf3e08E8dF289169EdE581

Please feel free to push / suggest style improvement & maybe we could also create issue for better styles on keep iterating their if this feels good for inital version 🙌

### CODE REVIEW

**Comment by technophile-04** [comment]
Just pushed a temporary solution to handle complex nested structs at [b6feb5a](https://github.com/BuidlGuidl/abi.ninja/pull/68/commits/b6feb5ae63d88d34f2d6edcddbd8ac539ae3c5b8)


https://github.com/BuidlGuidl/abi.ninja/assets/80153681/0fff4f2d-5d52-4dcc-b373-1ca7dd278992

**Review by portdeveloper — APPROVED** [review]
I think this looks great as it is currently! Amazing as always 🫡🫡🫡

**Comment by damianmarti** [comment]
@technophile-04 This is awesome!!!

**Comment by technophile-04** [comment]
Tysm all !! Merging this 🙌

**Pull request merged**
