### PR TITLE
Add skeleton loader when loading networks + Resize abi ninja logo

### PR DESCRIPTION
**Pull request by ByteAtATime**
## Description

Adds a skeleton loader for networks.

I set the height to exactly 38 pixels because that is the size that `react-select` has the select menu set at. I'm not sure if this is the best approach, but I think it works.

## Additional Information

- [x] I have read the [contributing docs](https://github.com/BuidlGuidl/abi.ninja/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/BuidlGuidl/abi.ninja/pulls)

## Related Issues

_Closes #98_

Your ENS/address: `byteatatime.eth`

### CODE REVIEW

**Comment by portdeveloper** [comment]
This is amazing! Thanks @ByteAtATime 

However do you think it would be better to override the default background color with `bg-neutral` ?

`className="skeleton max-w-xs w-44 relative h-[38px]"`
image

`className="skeleton bg-neutral max-w-xs w-44 relative h-[38px]"`
image



Also we may want to change the width and height of the Image component in index.tsx:
from 
`<Image src="/logo_inv.svg" alt="logo" width={128} height={128} className="mb-4" />`
to
`<Image src="/logo_inv.svg" alt="logo" width={119} height={87} className="mb-4" />` 

This is another reason why we have that little shift there.

Thanks for opening this PR 🫡🫡🫡

**Comment by technophile-04** [comment]
Thanks @ByteAtATime, could you please do the changes which Port suggested ?

**Comment by technophile-04** [comment]
Hey @ByteAtATime any update on this ? please let us know if you need any help 🙌

**Review by portdeveloper — APPROVED** [review]
lgtm

**Comment by ByteAtATime** [comment]
I'm sorry, I had a few other things to do. I see port has it figured out, thanks for that!

**Pull request merged**
