### PR TITLE
use next 13.3.4

### LINKED ISSUE #45: Dropdown wallet menu, inconsistent on PROD
Local env:

Prod dev:

----

- The :focus bg colors are different + paddings are off
- The cursor is different (local = pointer, prod = regular crosshair)
- ~~The ENS image was a cached thing (solved after clearing local storage).~~

I think we have encountered this before, right @technophile-04 ? It was caused because `yarn.lock` is not visible for Vercel when deploying and we get a different (daisyUI?) version

### PR DESCRIPTION
**Pull request by technophile-04**
### Description : 

Fixes #45, Actually it seems there was some bug in next 13.1 which was not processing  daisUI > 3.0  css during build updating next to latest should solve this as it was suggested here https://github.com/saadeghi/daisyui/issues/2303

Also didn't updated to latest / next 13.4 just to be safe since I heard there were some wierd issues faced by people using pages router when they introduced app router stable (although their docs says it is backward compatible with pages router)

### CODE REVIEW

**Comment by technophile-04** [comment]
https://abi-ninja-v2-git-v2-up-next-buidlguidldao.vercel.app 

Is working fine 🙌

**Comment by portdeveloper** [comment]
Looks good to me! 🫡

**Review by Pabl0cks — APPROVED** [review]
LGTM! Gj @technophile-04 researching and fixing it so quick! 🔥

**Comment by carletex** [comment]
Good stuff @technophile-04! Thank you!! <3

**Pull request merged**
