### PR TITLE
Fix typo in Etherscan API key env field

### PR DESCRIPTION
**Pull request by lukaw3d**
## Description

-
## Additional Information

- [x] I have read the [contributing docs](https://github.com/BuidlGuidl/abi.ninja/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/BuidlGuidl/abi.ninja/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Review by technophile-04 — COMMENTED** [review]
I think its nice to have it prefixed with mainnet.

**Comment by technophile-04** [comment]
Hey @lukaw3d just noticed that on prod we actually have `NEXT_PUBLIC_MAINNET_ETHERSCAN_API_KEY` setup we have it wrong in `networks.ts`
 https://github.com/BuidlGuidl/abi.ninja/blob/d0ebfcb4129e7031e2e4379af44b422b994b20d3/packages/nextjs/utils/scaffold-eth/networks.ts#L46

Could you update `networks.ts` instead? And revert changes to `.env.example`?

**Comment by lukaw3d** [comment]
:scream: yep

**Review by technophile-04 — APPROVED** [review]
Thanks @lukaw3d !! Looks great! 

---

cc @portdevelope not sure why the e2e test is failing. The test test which is failing seems to require heimdall URL which is already in configured in gh enviornment variables. I think probably since this PR is created from fork it is not able to access our gh ENV variable? 

Not super priority but would be great if we could fix this somehow 🙌

**Pull request merged**
