### PR TITLE
Fix rounding issue when converting to wei

### PR DESCRIPTION
**Pull request by lukaw3d**
## Description

Related to https://github.com/BuidlGuidl/abi.ninja/pull/135

https://abi.ninja/0xde30da39c46104798bb5aa3fe8b9e0e1f348163f/1?methods=transfer
|  |  |
| --- | --- |
| abi ninja_0xde30da39c46104798bb5aa3fe8b9e0e1f348163f_1_methods=transfer | abi ninja_0xde30da39c46104798bb5aa3fe8b9e0e1f348163f_1_methods=transfer (1) |

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [x] I have read the [contributing docs](https://github.com/BuidlGuidl/abi.ninja/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/BuidlGuidl/abi.ninja/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Comment by lukaw3d** [comment]
Upstreamed https://github.com/scaffold-eth/scaffold-eth-2/pull/940

**Comment by technophile-04** [comment]
Hey @lukaw3d can we add final changes from https://github.com/scaffold-eth/scaffold-eth-2/pull/940/files here?

**Comment by lukaw3d** [comment]
:+1:

**Review by technophile-04 — APPROVED** [review]
Thanks @lukaw3d !!

**Pull request merged**
