### PR TITLE
Readme + link

### PR DESCRIPTION
**Pull request by carletex**
Created a simple README (similar to what we had in v1). We might want to iterate on it, but this could be enough for release.

Also add the right link to the repo and removed the support one.

### CODE REVIEW

**Review by portdeveloper — APPROVED** [review]
Looks great!
maybe we can say You just need ... Instead of Just need on line 3 but im being extremely nitpicky here

**Comment by carletex** [comment]
Love the nitpicking @portdeveloper ! Changed https://github.com/BuidlGuidl/abi.ninja/pull/52/commits/501c2fe1d9be8dd0cc2f48c5bf69977f8769732a

It'll probably need a complete rewrite at some point haha

**Review by technophile-04 — APPROVED** [review]
LGTM for initial version ! We can maybe update the SS in later iteration too !

**Review by Pabl0cks — APPROVED** [review]
Nice initial version @carletex! 🙌

We can iterate on it when we add heimdall, struct/array inputs, previous to the announcement, explaining the different features and updating the sshots as @technophile-04 said.

**Pull request merged**
