### PR TITLE
Fix style issues in Contract detail page

### LINKED ISSUE #54: Some styles issues
Снимок экрана 2024-02-06 в 02 32 22

1. Close icon isn't centered with method name
2. Input has additional left margin
3. Result has no gap with read button. Additionally, I think result border radius should be changed
4. Method name has too small top margin

Снимок экрана 2024-02-06 в 02 35 56

5. No gap between text and refresh button
6. Copy button doesn't have hover effect (minor)

Снимок экрана 2024-02-06 в 02 39 59

7. No hover on close button, but hover on menu button

Tested with 0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d contract

### PR DESCRIPTION
**Pull request by Pabl0cks**
## Description

- Fixes #54 
- Fix zero inputs send button positioning (was overlaping close icon)

> Copy button doesn't have hover effect (minor)

Haven't fixed this one because I think it means changing `<Address>` component. Can add it a `hover:opacity-70` effect, but maybe we should do it in SE-2 then.

If you find any other style issue, lmk to fix! 🙌♥

### CODE REVIEW

**Comment by rin-st** [comment]
Looks great, thank you!

Regarding mobile menu burger/close button, I meant they should be the same, changing bg on hover. But I forgot that no one sees hover on mobiles, so that hover effects doesn't matter 🤷‍♂️ .

**Review by rin-st — APPROVED** [review]

**Review by portdeveloper — APPROVED** [review]
I see no issues as well @Pabl0cks ! Great work 👍

**Review by technophile-04 — APPROVED** [review]
This is looking great !!

Just an idea that came to my mind : 

Screenshot 2024-02-08 at 3 22 51 PM


maybe in placeholder should we add "address or ENS"? 

Just to be clear with new people they can directly use ENS too

We can just do : 

```ts
const addressInputProps = { ...inputProps, placeholder: "address or ENS" };
return <AddressInput {...addressInputProps} />;
``` 
Here : https://github.com/BuidlGuidl/abi.ninja/blob/369826e0d84a409147ae116b9a3e0f894576ba1e/packages/nextjs/components/scaffold-eth/Contract/ContractInput.tsx#L35

What do you all think?

**Comment by Pabl0cks** [comment]
> maybe in placeholder should we add "address or ENS"?
> 
> Just to be clear with new people they can directly use ENS too

Love that!! At some point I had the same thought, but forgot! I think BG crew would put ENS instinctively but external users can make use of that little help.

Pushing that change 🙌

**Comment by technophile-04** [comment]
Tysm Pablo !!

**Pull request merged**
