### PR TITLE
fix any abi fail

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

- Added a timeout for anyabi so that it fixes current issue
- used useQuery for fetching data so that we cache request and don't make same request when going from home page => contract address page

### CODE REVIEW

**Comment by technophile-04** [comment]
Ohh I think I know why some of the test are failing, will update it soon

**Comment by technophile-04** [comment]
Seem like Parex chain is rpc down that's why the last test seems to fail :/

image

https://chainlist.org/chain/322202

Will update that test to consider different chain

**Review by portdeveloper — APPROVED** [review]
Just ran the tests locally and everything works great!

amazing work as always!

**Review by technophile-04 — COMMENTED** [review]
Thanks @portdeveloper! Merging this

**Pull request merged**
